// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "Rajesh Yadav",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "Olandganj, Jaunpur, Uttar Pradesh",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Sunita Singh",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "Shahganj, Jaunpur, Uttar Pradesh",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Anil Mishra",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "Kerakat, Jaunpur, Uttar Pradesh",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Pooja Verma",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "Badlapur, Jaunpur, Uttar Pradesh",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Sanjay Gupta",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "Machhlishahr, Jaunpur, Uttar Pradesh",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Neha Singh",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "Mariahu, Jaunpur, Uttar Pradesh",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Vivek Tiwari",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "Jafarabad, Jaunpur, Uttar Pradesh",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Priya Yadav",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "Sadar, Jaunpur, Uttar Pradesh",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Manoj Patel",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "Sujanganj, Jaunpur, Uttar Pradesh",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "Kavita Sharma",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "Mungra Badshahpur, Jaunpur, Uttar Pradesh",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "Aarav Yadav",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "Olandganj, Jaunpur, Uttar Pradesh",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Ananya Singh",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Shahganj, Jaunpur, Uttar Pradesh",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Aditya Mishra",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Kerakat, Jaunpur, Uttar Pradesh",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Priyanshi Verma",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Badlapur, Jaunpur, Uttar Pradesh",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Ayush Gupta",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Machhlishahr, Jaunpur, Uttar Pradesh",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Shreya Singh",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Mariahu, Jaunpur, Uttar Pradesh",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Abhishek Tiwari",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Jafarabad, Jaunpur, Uttar Pradesh",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Khushi Yadav",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Sadar, Jaunpur, Uttar Pradesh",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Rohit Patel",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Sujanganj, Jaunpur, Uttar Pradesh",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "Muskan Sharma",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "Mungra Badshahpur, Jaunpur, Uttar Pradesh",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "Ramesh Yadav",
    students: ["Aarav Yadav"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "Olandganj, Jaunpur, Uttar Pradesh",
  },
  {
    id: 2,
    name: "Suresh Singh",
    students: ["Ananya Singh"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "Shahganj, Jaunpur, Uttar Pradesh",
  },
  {
    id: 3,
    name: "Rajendra Mishra",
    students: ["Aditya Mishra"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Kerakat, Jaunpur, Uttar Pradesh",
  },
  {
    id: 4,
    name: "Mahendra Verma",
    students: ["Priyanshi Verma", "Ayush Gupta"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Badlapur, Jaunpur, Uttar Pradesh",
  },
  {
    id: 5,
    name: "Sunil Gupta",
    students: ["Shreya Singh"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Machhlishahr, Jaunpur, Uttar Pradesh",
  },
  {
    id: 6,
    name: "Vijay Tiwari",
    students: ["Abhishek Tiwari"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Mariahu, Jaunpur, Uttar Pradesh",
  },
  {
    id: 7,
    name: "Dilip Yadav",
    students: ["Khushi Yadav", "Rohit Patel"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Jafarabad, Jaunpur, Uttar Pradesh",
  },
  {
    id: 8,
    name: "Mohan Patel",
    students: ["Muskan Sharma"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Sadar, Jaunpur, Uttar Pradesh",
  },
  {
    id: 9,
    name: "Prakash Sharma",
    students: ["Aarav Yadav", "Ananya Singh"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Sujanganj, Jaunpur, Uttar Pradesh",
  },
  {
    id: 10,
    name: "Naresh Singh",
    students: ["Aditya Mishra"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "Mungra Badshahpur, Jaunpur, Uttar Pradesh",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    teachers: ["Ashok Dubey", "Renu Maurya"],
  },
  {
    id: 2,
    name: "English",
    teachers: ["Dinesh Shukla", "Meena Tripathi"],
  },
  {
    id: 3,
    name: "Physics",
    teachers: ["Rakesh Singh", "Nisha Srivastava"],
  },
  {
    id: 4,
    name: "Chemistry",
    teachers: ["Suresh Yadav", "Anita Verma"],
  },
  {
    id: 5,
    name: "Biology",
    teachers: ["Arun Kumar", "Shalini Gupta"],
  },
  {
    id: 6,
    name: "History",
    teachers: ["Mahesh Mishra", "Rekha Singh"],
  },
  {
    id: 7,
    name: "Geography",
    teachers: ["Vijay Tiwari", "Asha Yadav"],
  },
  {
    id: 8,
    name: "Art",
    teachers: ["Ramesh Patel", "Seema Sharma"],
  },
  {
    id: 9,
    name: "Music",
    teachers: ["Pankaj Dubey", "Sunita Maurya"],
  },
  {
    id: 10,
    name: "Literature",
    teachers: ["Ajay Shukla", "Kiran Tripathi"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Deepak Singh",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Suman Srivastava",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Mohan Yadav",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Rachna Verma",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Naveen Gupta",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Geeta Mishra",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Pradeep Singh",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Shweta Tiwari",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Rajiv Yadav",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Neelam Patel",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Vinod Sharma",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Madhuri Dubey",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Santosh Maurya",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Vandana Shukla",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Amit Tripathi",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Ritu Singh",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Kamal Srivastava",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Jyoti Yadav",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Harish Verma",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Sangeeta Gupta",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Amit Kumar",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Ravi Singh",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Nitin Mishra",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Rakesh Verma",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Sanjay Yadav",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Manish Gupta",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Rohit Singh",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Vikas Tiwari",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Rajendra Yadav",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Archana Sharma",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Vishal Mishra",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Prashant Singh",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Swati Verma",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Gaurav Gupta",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Manoj Yadav",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Poonam Singh",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Anurag Tiwari",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Ravi Yadav",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Abhishek Mishra",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Naveen Singh",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Rajesh Yadav",
    student: "Rajesh Yadav",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rajesh Yadav",
    student: "Rajesh Yadav",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Rajesh Yadav",
    student: "Rajesh Yadav",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Rajesh Yadav",
    student: "Rajesh Yadav",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Rajesh Yadav",
    student: "Rajesh Yadav",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Rajesh Yadav",
    student: "Rajesh Yadav",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Rajesh Yadav",
    student: "Rajesh Yadav",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Rajesh Yadav",
    student: "Rajesh Yadav",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Rajesh Yadav",
    student: "Rajesh Yadav",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Rajesh Yadav",
    student: "Rajesh Yadav",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2026, 8, 9, 8, 0),
    end: new Date(2026, 8, 9, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 8, 9, 9, 0),
    end: new Date(2026, 8, 9, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 8, 9, 10, 0),
    end: new Date(2026, 8, 9, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 8, 9, 11, 0),
    end: new Date(2026, 8, 9, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2026, 8, 9, 13, 0),
    end: new Date(2026, 8, 9, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2026, 8, 9, 14, 0),
    end: new Date(2026, 8, 9, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 8, 10, 9, 0),
    end: new Date(2026, 8, 10, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 8, 10, 10, 0),
    end: new Date(2026, 8, 10, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 8, 10, 11, 0),
    end: new Date(2026, 8, 10, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2026, 8, 10, 14, 0),
    end: new Date(2026, 8, 10, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2026, 8, 11, 8, 0),
    end: new Date(2026, 8, 11, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 8, 11, 10, 0),
    end: new Date(2026, 8, 11, 10, 45),
  },

  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2026, 8, 11, 13, 0),
    end: new Date(2026, 8, 11, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2026, 8, 11, 14, 0),
    end: new Date(2026, 8, 11, 14, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 8, 12, 9, 0),
    end: new Date(2026, 8, 12, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2026, 8, 12, 10, 0),
    end: new Date(2026, 8, 12, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 8, 12, 11, 0),
    end: new Date(2026, 8, 12, 11, 45),
  },

  {
    title: "History",
    allDay: false,
    start: new Date(2026, 8, 12, 14, 0),
    end: new Date(2026, 8, 12, 14, 45),
  },
  {
    title: "Math",
    allDay: false,
    start: new Date(2026, 8, 13, 8, 0),
    end: new Date(2026, 8, 13, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2026, 8, 13, 9, 0),
    end: new Date(2026, 8, 13, 9, 45),
  },

  {
    title: "Physics",
    allDay: false,
    start: new Date(2026, 8, 13, 11, 0),
    end: new Date(2026, 8, 13, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2026, 8, 13, 13, 0),
    end: new Date(2026, 8, 13, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2026, 8, 13, 14, 0),
    end: new Date(2026, 8, 13, 14, 45),
  },
];